# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = XCPLib
DESTDIR = ../build/Debug
CONFIG += C++11
DEFINES =
OBJECTS_DIR += debug
INCLUDEPATH += .
DEPENDPATH += .
include(XCPLib.pri)
